controllers/CategoryController.php
<?php

namespace app\controllers;

use Yii;
use app\entities\Category;
use app\search\CategorySearch;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * CategoryController implements the CRUD actions for Category model.
 */
class CategoryController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::class,
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Category models.
     * @return mixed
     */
    public function actionIndex()
    {
        $categores=Category::find()->where(['parent_id'=>null]);
        $categoresDataProvider= new ActiveDataProvider([
            'query' => $categores,
            'pagination' => [
                'pageSize' => 24,
            ],
        ]);
        return $this->render('index', [
            'categoresDataProvider'=>$categoresDataProvider
        ]);
    }

    public function actionCategory($id){
        $page_size = Yii::$app->request->get('per-page');
        $page_size = isset( $page_size ) ? intval($page_size) : 1;
        $category=Category::find()->where(['id'=>$id])->one();
        $booksDataProvider= new ActiveDataProvider([
            'query' => $category->getBooks(),
            'pagination' => [
                'pageSize' =>  $page_size,
            ],
        ]);
        return $this->render('category',[
            'category'=>$category,
            'booksDataProvider'=>$booksDataProvider
        ]);
    }


    
}

views/category/_one.php
<?php

/**
 * @var $model app\entities\Category
 */

use yii\helpers\Html;
use yii\helpers\Url;
?>

<div class="col-md-3 resent-grid recommended-grid movie-video-grid">
    <div class="resent-grid-img recommended-grid-img">
        <h3>
            <?= Html::a( $model->title,Url::to(['/category/category','id'=>$model->id])) ?>
        </h3>
        
    </div>
    <div class="resent-grid-info recommended-grid-info recommended-grid-movie-info">
        <h5>
            <?= Html::a( $model->description,Url::to(['/category/category','id'=>$model->id])) ?>
       </h5>
    </div>
</div>

views/category/_oneBook.php
<?php 

/** @var $model app\entities\Book */

use yii\helpers\Html;
use yii\helpers\Url;
?>

<div class="col-md-4 resent-grid recommended-grid movie-video-grid">
    <div class="resent-grid-img recommended-grid-img">
        <?= Html::a(Html::img($model->imageUrl),Url::to(['/book','id'=>$model->id])) ?>
        <div class="clck small-clck">
            <span class="glyphicon glyphicon-time" aria-hidden="true"></span>
        </div>
        <div class="resent-grid-info recommended-grid-info">
            <h5>
                <?= Html::a($model->title,Url::to(['/book','id'=>$model->id])) ?>
            </h5>
            <div class="slid-bottom-grids">
                <div class="slid-bottom-grid">
                    <p class="author author-info">
                        <?php foreach ($model->autors as $autor){ ?>
                            <?= Html::a($autor->first_name.' '.$autor->second_name,Url::to(['/autor','id'=>$autor->id]))?>
                        <?php } ?>
                    </p>
                </div>
                <div class="slid-bottom-grid slid-bottom-right">
                    <p class="views views-info">
                        <?php foreach ($model->tags as $tag){ ?>
                            <?= Html::a('#'.$tag->title, Url::to(['/tag','id'=>$tag->id]))?>
                        <?php } ?>
                    </p>
                </div>
                <div class="clearfix"> </div>
            </div>
        </div>
</div>

views/category/category.php
<?php

/**
 * @var $this yii\web\View
 * @var  $category app\entities\Category;
 */

use yii\widgets\ListView;
use app\widgets\linkPager\Pager;
$this->title = $category->title;
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="recommended" id="category">
    <div class="recommended-grids english-grid">
        <div class="recommended-info">
            <div class="heading">
                <h3><?= $this->title ?></h3>
            </div>
            <div class="heading-right">
                <a  href="#small-dialog8" class="play-icon popup-with-zoom-anim">Subscribe</a>
            </div>
            <div class="clearfix"> </div>
        </div>
        <?php
        if(empty($category->books)){
            foreach ($category->childs as $child){
                echo $this->render('_one',[
                    'model'=>$child
                ]);
            }
        }else{
            echo "<div class='col-xs-12 col-sm-9'>";
            echo ListView::widget([
                'dataProvider'  => $booksDataProvider,
                'itemView'      => '_oneBook',
                'summary' => false,
                'layout'=>"{items}\n</div><div class='col-xs-12 col-sm-9'>{pager}",
                'pager' => [
                    'class' => Pager::class,
                    'firstPageLabel' => Yii::t('app','First'),
                    'lastPageLabel' => Yii::t('app','Last'),
                    'maxButtonCount' => 4,
                    'options' => [
                        'class' => 'pagination',
                        'style' => 'display:inline-block;float:left;margin:10px 10px;width:auto;height:28px;'
                    ],
                    'sizeListHtmlOptions' => [
                        'class' => 'form-control',
                        'style' => 'display:inline-block;float:left;margin:10px 10px;width:auto;height:28px;'
                    ],
                    'goToPageHtmlOptions' => [
                        'class' => 'form-control',
                        'id'=>'ToPage',
                        'style' => 'display:inline-block;float:left;margin:10px 10px;width:auto;height:28px;'
                    ],
                ],
            ]);
        } ?>
        </div>
        <div class="clearfix"> </div>
    </div>
</div>

views/category/index.php
<?php

/* @var $this yii\web\View */

use yii\widgets\ListView;

$this->title = 'Categories';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="recommended">
    <div class="recommended-grids english-grid">
        <div class="recommended-info">
            <div class="heading">
                <h3><?= $this->title ?></h3>
            </div>
            <div class="heading-right">
                <a  href="#small-dialog8" class="play-icon popup-with-zoom-anim">Subscribe</a>
            </div>
            <div class="clearfix"> </div>
        </div>
        <?= ListView::widget([
            'dataProvider'  => $categoresDataProvider,
            'itemView'      => '_one',
            'pager' => [
                'firstPageLabel' => Yii::t('app','First'),
                'lastPageLabel' => Yii::t('app','Last'),
                'prevPageLabel' => '<span class="fa fa-angle-left"></span>',
                'nextPageLabel' => '<span class="fa fa-angle-right"></span>',
            ],
        ]) ?>

        <div class="clearfix"> </div>
    </div>
</div>